function getHelperClient(helperObjectName)
    local function getHelperObject()
        for _, object in ipairs(getAllObjects()) do
            if object.getName() == helperObjectName then return object end
        end
        error('missing object "' .. helperObjectName .. '"')
    end
    local helperObject = false
    local function getCallWrapper(functionName)
        helperObject = helperObject or getHelperObject()
        if not helperObject.getVar(functionName) then error('missing ' .. helperObjectName .. '.' .. functionName) end
        return function(parameters) return helperObject.call(functionName, parameters) end
    end
    return setmetatable({}, { __index = function(t, k) return getCallWrapper(k) end })
end

local _systemHelper = getHelperClient('TI4_SYSTEM_HELPER')

function onClickNeighbors(systemObject)
    local hex = _systemHelper.hexFromPosition(systemObject.getPosition())
    local neighborsHexes = _systemHelper.hexNeighborsWithHyperlanes(hex)
    local system = _systemHelper.systemFromPosition(systemObject.getPosition())
    log("Getting neighbors for system " .. system.string)
    for _, nHex in pairs(neighborsHexes) do
        local nSystem = _systemHelper.systemFromPosition(_systemHelper.hexToPosition(nHex))
        if nSystem and nSystem.string then
            log(nSystem.string)
        end
    end
end

function onObjectSpawn(object)
    local _systems = _systemHelper.systems()
    if _systems[object.getGUID()] and not _systems[object.getGUID()].hyperlane then
        assert(type(object) == 'userdata')
        assert(_systems[object.getGUID()])
        object.addContextMenuItem('Get Neighbors', function() onClickNeighbors(object) end, false)
    end
end

function onLoad(saveState)
    local function delayedAddContextMenuItems()
        local _systems = _systemHelper.systems()
        for _, object in ipairs(getAllObjects()) do
            if _systems[object.getGUID()] and not _systems[object.getGUID()].hyperlane then
                assert(type(object) == 'userdata')
                assert(_systems[object.getGUID()])
                object.addContextMenuItem('Get Neighbors', function() onClickNeighbors(object) end, false)
            end
        end
    end
    Wait.frames(delayedAddContextMenuItems, 9)
end